
export const SET_DANH_SACH_PHONG_VE = 'SET_DANH_SACH_PHONG_VE';
export const SET_DANH_SACH_GHE_DANG_DAT = 'SET_DANH_SACH_GHE_DANG_DAT';
export const SET_RONG_DANH_SACH_GHE_DANG_DAT = 'SET_RONG_DANH_SACH_GHE_DANG_DAT';
export const SET_ACTIVE_KEY_TAB = 'SET_ACTIVE_KEY_TAB'