
export const SET_DANH_SACH_BANNER = 'SET_DANH_SACH_BANNER'
export const SET_DANH_SACH_PHIM = 'SET_DANH_SACH_PHIM'
export const SET_DANH_SACH_PHIM_DANG_CHIEU = 'SET_DANH_SACH_PHIM_DANG_CHIEU'
export const SET_DANH_SACH_PHIM_SAP_CHIEU = 'SET_DANH_SACH_PHIM_SAP_CHIEU'
export const SET_CHI_TIET_PHIM = 'SET_CHI_TIET_PHIM'
export const SEARCH_DANH_SACH_PHIM = 'SEARCH_DANH_SACH_PHIM'