
export const SET_THONG_TIN_DANG_NHAP = 'SET_THONG_TIN_DANG_NHAP';
export const SET_THONG_TIN_NGUOI_DUNG = 'SET_THONG_TIN_NGUOI_DUNG';
export const SET_DANH_SACH_NGUOI_DUNG = 'SET_DANH_SACH_NGUOI_DUNG';
export const SET_DANH_SACH_LOAI_NGUOI_DUNG = 'SET_DANH_SACH_LOAI_NGUOI_DUNG'
export const SET_THONG_TIN_NGUOI_DUNG_CHINH_SUA = 'SET_THONG_TIN_NGUOI_DUNG_CHINH_SUA'